@startuml 4-3.png
skinparam monochrome true
skinparam defaultFontName Ricty
hide footbox
skinparam classAttributeIconSize 0

title ステートパターン

class 社長 {
    +起立させる()
    +意見を聞く()
}

class 社員 {
    +起立する()
    +給料を計算する()
    +主任にする()
    +担当にする()
}

class 役職 {
    +起立する()
    +給料を計算する()
    +主任にする()
    +担当にする()
}

class 担当 {
    +起立する()
    +給料を計算する()
    +意見を聞く()
    +主任にする()
}

class 主任 {
    +起立する()
    +給料を計算する()
    +意見を聞く()
    +担当にする()
}

社長 -> 社員
社員 -> 役職
役職 <|-- 担当
役職 <|-- 主任

@enduml
