@startuml 4-5-4.png
skinparam monochrome true
skinparam defaultFontName Ricty
hide footbox
skinparam classAttributeIconSize 0

title アダプターパターン(委譲 has a)

class 社長 {
}

class 社員 {
    +起立する()
    +意見を聞く()
}

class 通訳社員 {
    +起立する()
    -キリツする()
}

class 派遣社員 {
    -キリツする()
}

社長 -> 社員
社員 <|-- 通訳社員
通訳社員 -> 派遣社員

note left of 通訳社員::起立する
  派遣社員. キリツする()
end note

@enduml
